# Generated by Django 5.1.4 on 2025-01-13 17:07

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("basket", "0012_line_code"),
		("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
		("partner", "0006_auto_20200724_0909"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AlterModelOptions(
			name="basket",
			options={
				"base_manager_name": "prefetch_manager",
				"verbose_name": "Basket",
				"verbose_name_plural": "Baskets",
			},
		),
		migrations.AlterModelOptions(
			name="line",
			options={
				"base_manager_name": "prefetch_manager",
				"ordering": ["date_created", "pk"],
				"verbose_name": "Basket line",
				"verbose_name_plural": "Basket lines",
			},
		),
		migrations.AlterModelOptions(
			name="lineattribute",
			options={
				"base_manager_name": "prefetch_manager",
				"verbose_name": "Line attribute",
				"verbose_name_plural": "Line attributes",
			},
		),
		migrations.AlterModelManagers(
			name="basket",
			managers=[
				("objects", django.db.models.manager.Manager()),
				("prefetch_manager", django.db.models.manager.Manager()),
			],
		),
		migrations.AlterModelManagers(
			name="line",
			managers=[
				("objects", django.db.models.manager.Manager()),
				("prefetch_manager", django.db.models.manager.Manager()),
			],
		),
		migrations.AlterModelManagers(
			name="lineattribute",
			managers=[
				("objects", django.db.models.manager.Manager()),
				("prefetch_manager", django.db.models.manager.Manager()),
			],
		),
		migrations.AlterField(
			model_name="basket",
			name="owner",
			field=auto_prefetch.ForeignKey(
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="baskets",
				to=settings.AUTH_USER_MODEL,
				verbose_name="Owner",
			),
		),
		migrations.AlterField(
			model_name="line",
			name="basket",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="lines",
				to="basket.basket",
				verbose_name="Basket",
			),
		),
		migrations.AlterField(
			model_name="line",
			name="product",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="basket_lines",
				to="catalogue.product",
				verbose_name="Product",
			),
		),
		migrations.AlterField(
			model_name="line",
			name="stockrecord",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="basket_lines",
				to="partner.stockrecord",
			),
		),
		migrations.AlterField(
			model_name="lineattribute",
			name="line",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="attributes",
				to="basket.line",
				verbose_name="Line",
			),
		),
		migrations.AlterField(
			model_name="lineattribute",
			name="option",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				to="catalogue.option",
				verbose_name="Option",
			),
		),
	]
