# Generated by Django 5.1.1 on 2024-09-26 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("catalogue", "0028_product_video_url"),
	]

	operations = [
		migrations.AddField(
			model_name="product",
			name="priority",
			field=models.SmallIntegerField(
				db_index=True,
				default=0,
				help_text="The highest priority products are shown first",
				validators=[django.core.validators.MinValueValidator(-1)],
				verbose_name="Priority",
			),
		),
	]
