from django.urls import path

from . import views

app_name = "pixio"
urlpatterns = [
	path("", views.index, name="index"),
	path("shop-compare/", views.shop_compare, name="shop-compare"),
	path(
		"shop-order-tracking/",
		views.shop_order_tracking,
		name="shop-order-tracking",
	),
	path("blog-dark-2-column/", views.blog_dark_2_column, name="blog-dark-2-column"),
	path(
		"blog-dark-2-column-sidebar/",
		views.blog_dark_2_column_sidebar,
		name="blog-dark-2-column-sidebar",
	),
	path("blog-dark-3-column/", views.blog_dark_3_column, name="blog-dark-3-column"),
	path(
		"blog-dark-half-image/",
		views.blog_dark_half_image,
		name="blog-dark-half-image",
	),
	path(
		"blog-light-2-column/",
		views.blog_light_2_column,
		name="blog-light-2-column",
	),
	path(
		"blog-light-2-column-sidebar/",
		views.blog_light_2_column_sidebar,
		name="blog-light-2-column-sidebar",
	),
	path(
		"blog-light-half-image/",
		views.blog_light_half_image,
		name="blog-light-half-image",
	),
	path("blog-exclusive/", views.blog_exclusive, name="blog-exclusive"),
	path("blog-left-sidebar/", views.blog_left_sidebar, name="blog-left-sidebar"),
	path("blog-right-sidebar/", views.blog_right_sidebar, name="blog-right-sidebar"),
	path("blog-both-sidebar/", views.blog_both_sidebar, name="blog-both-sidebar"),
	path("blog-wide-sidebar/", views.blog_wide_sidebar, name="blog-wide-sidebar"),
	path("blog-archive/", views.blog_archive, name="blog-archive"),
	path("blog-author/", views.blog_author, name="blog-author"),
	path("blog-category/", views.blog_category, name="blog-category"),
	path("blog-tag/", views.blog_tag, name="blog-tag"),
	path("post-standard/", views.post_standard, name="post-standard"),
	path("post-left-sidebar/", views.post_left_sidebar, name="post-left-sidebar"),
	path("post-header-image/", views.post_header_image, name="post-header-image"),
	path("post-slide-show/", views.post_slide_show, name="post-slide-show"),
	path("post-side-image/", views.post_side_image, name="post-side-image"),
	path("post-gallery/", views.post_gallery, name="post-gallery"),
	path(
		"post-gallery-alternative/",
		views.post_gallery_alternative,
		name="post-gallery-alternative",
	),
	path(
		"post-open-gutenberg/",
		views.post_open_gutenberg,
		name="post-open-gutenberg",
	),
	path("post-link/", views.post_link, name="post-link"),
	path("post-audio/", views.post_audio, name="post-audio"),
	path("post-video/", views.post_video, name="post-video"),
	path("portfolio-tiles/", views.portfolio_tiles, name="portfolio-tiles"),
	path("collage-style-1/", views.collage_style_1, name="collage-style-1"),
	path("collage-style-2/", views.collage_style_2, name="collage-style-2"),
	path("masonry-grid/", views.masonry_grid, name="masonry-grid"),
	path("cobble-style-1/", views.cobble_style_1, name="cobble-style-1"),
	path("cobble-style-2/", views.cobble_style_2, name="cobble-style-2"),
	path(
		"portfolio-thumbs-slider/",
		views.portfolio_thumbs_slider,
		name="portfolio-thumbs-slider",
	),
	path(
		"portfolio-film-strip/",
		views.portfolio_film_strip,
		name="portfolio-film-strip",
	),
	path("carousel-showcase/", views.carousel_showcase, name="carousel-showcase"),
	path(
		"portfolio-split-slider/",
		views.portfolio_split_slider,
		name="portfolio-split-slider",
	),
	path(
		"portfolio-details-1/",
		views.portfolio_details_1,
		name="portfolio-details-1",
	),
	path(
		"portfolio-details-2/",
		views.portfolio_details_2,
		name="portfolio-details-2",
	),
	path(
		"portfolio-details-3/",
		views.portfolio_details_3,
		name="portfolio-details-3",
	),
	path(
		"portfolio-details-4/",
		views.portfolio_details_4,
		name="portfolio-details-4",
	),
	path(
		"portfolio-details-5/",
		views.portfolio_details_5,
		name="portfolio-details-5",
	),
	path("about-us/", views.about_us, name="about-us"),
	path("pricing-table/", views.pricing_table, name="pricing-table"),
	path("our-gift-vouchers/", views.our_gift_vouchers, name="our-gift-vouchers"),
	path("what-we-do/", views.what_we_do, name="what-we-do"),
	path("faq/", views.faq, name="faq"),
	path("our-team/", views.our_team, name="our-team"),
	path("contact-us/", views.contact_us, name="contact-us"),
	path("account-dashboard/", views.account_dashboard, name="account-dashboard"),
	path("account-orders/", views.account_orders, name="account-orders"),
	path(
		"account-order-details/",
		views.account_order_details,
		name="account-order-details",
	),
	path(
		"account-order-confirmation/",
		views.account_order_confirmation,
		name="account-order-confirmation",
	),
	path("account-downloads/", views.account_downloads, name="account-downloads"),
	path(
		"account-return-request/",
		views.account_return_request,
		name="account-return-request",
	),
	path(
		"account-return-request-detail/",
		views.account_return_request_detail,
		name="account-return-request-detail",
	),
	path(
		"account-refund-request-confirmed/",
		views.account_refund_request_confirmed,
		name="account-refund-request-confirmed",
	),
	path("account-profile/", views.account_profile, name="account-profile"),
	path("account-address/", views.account_address, name="account-address"),
	path(
		"account-shipping-methods/",
		views.account_shipping_methods,
		name="account-shipping-methods",
	),
	path(
		"account-payment-methods/",
		views.account_payment_methods,
		name="account-payment-methods",
	),
	path("account-review/", views.account_review, name="account-review"),
	path(
		"account-billing-address/",
		views.account_billing_address,
		name="account-billing-address",
	),
	path(
		"account-shipping-address/",
		views.account_shipping_address,
		name="account-shipping-address",
	),
	path(
		"account-cancellation-requests/",
		views.account_cancellation_requests,
		name="account-cancellation-requests",
	),
]
